server:
  port: 8010

spring:
  application:
    name: country-server
  security:
    user:
      name: app-user
      password: c1e3d0fa-5aa8-4be7-83f7-32974dd617bf
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
