server:
  port: 8010

spring:
  application:
    name: country-server

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true


server-service:
  service-name: country-service
  username: app-user
  password: c1e3d0fa-5aa8-4be7-83f7-32974dd617bf
