server:
  port: 8080

spring:
  application:
    name: country-service
  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log

